layout_spectrum: 1
color:
  saturation: 1
  brandStrength: 0.6959139
  lightness: 0.4226638
  rhythmicContrast: 1
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
typography_spectrum: 0.2422127
name: 'Litmus '
